CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  avatar TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE videos (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  active_thumbnail_url TEXT,
  title TEXT NOT NULL,
  preview_count INT DEFAULT 0,
  is_active BOOL DEFAULT FALSE,
  video_length TEXT,
  youtube_display_name TEXT,
  youtube_url TEXT,
  tags TEXT [],
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE previews (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  thumbnail_url TEXT NOT NULL,
  is_active BOOL DEFAULT FALSE,
  title TEXT NOT NULL,
  description TEXT,
  video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);